# Generated by Django 3.2.7 on 2021-10-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0003_auto_20211004_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='type',
            field=models.CharField(choices=[('OTC', 'Over the Counter '), ('PO', 'Pharmacy Only'), ('P', 'Prescription')], max_length=50),
        ),
    ]
