# Generated by Django 3.2.7 on 2021-10-18 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medication', '0004_alter_medication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='units_moved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='completed_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=1, null=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='medication.pharmacy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
