# Generated by Django 3.2.7 on 2021-10-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0005_auto_20211018_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='precautions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='side_effects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
    ]
