# Generated by Django 3.2.7 on 2021-10-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0006_auto_20211025_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='medication',
        ),
    ]
