# Generated by Django 3.2.7 on 2021-10-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0007_remove_pharmacy_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
