# Generated by Django 3.2.7 on 2021-12-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0008_auto_20211025_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='scientific_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacystock',
            unique_together={('medication', 'pharmacy')},
        ),
    ]
