# Generated by Django 3.2.7 on 2021-12-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0009_auto_20211207_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacystock',
            name='stock',
        ),
        migrations.AddField(
            model_name='pharmacystock',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
