# Generated by Django 3.2.7 on 2022-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0010_auto_20211210_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='location_lat',
            field=models.DecimalField(decimal_places=40, max_digits=45),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='location_long',
            field=models.DecimalField(decimal_places=40, max_digits=45),
        ),
    ]
