# Generated by Django 3.2.7 on 2022-02-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0011_auto_20220131_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacystock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
