# Generated by Django 3.2.7 on 2022-02-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0012_alter_pharmacystock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='measurement',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
