# Generated by Django 3.2.7 on 2022-03-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0013_medication_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='socket_security_code',
            field=models.CharField(default='ferf4035-grt-bjd-tGFHYHtm545-0-g-mvsvfgbgxxbgBNFVC', max_length=60),
        ),
    ]
