# Generated by Django 3.2.7 on 2022-04-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0014_pharmacy_socket_security_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='socket_security_code',
        ),
    ]
