# Generated by Django 3.2.7 on 2022-05-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0015_remove_pharmacy_socket_security_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
