# Generated by Django 3.2.7 on 2022-05-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0016_pharmacy_is_online'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
