# Generated by Django 3.2.7 on 2021-09-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='fsa@fs.ba', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
