# Generated by Django 3.2.7 on 2021-12-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_d_o_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='d_o_b',
            field=models.DateField(null=True),
        ),
    ]
