# Generated by Django 3.2.7 on 2022-01-31 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20211211_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentRiderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lat', models.DecimalField(decimal_places=40, max_digits=45, null=True)),
                ('long', models.DecimalField(decimal_places=40, max_digits=45, null=True)),
                ('rider_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='authentication.riderprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
