# Generated by Django 3.2.7 on 2022-02-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0012_alter_pharmacystock_price'),
        ('authentication', '0006_currentriderlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='medication.pharmacy'),
        ),
    ]
