# Generated by Django 3.2.7 on 2022-02-02 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0012_alter_pharmacystock_price'),
        ('authentication', '0007_alter_pharmacistprofile_pharmacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacylicense',
            name='pharmacist_profile',
        ),
        migrations.AddField(
            model_name='pharmacylicense',
            name='pharmacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='medication.pharmacy'),
            preserve_default=False,
        ),
    ]
