# Generated by Django 3.2.7 on 2022-02-07 08:45

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20220202_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[core.utils.validators.validate_password]),
        ),
    ]
