# Generated by Django 3.2.7 on 2022-02-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacylicense',
            name='name',
            field=models.CharField(choices=[('business_permit', 'business_permit'), ('annual_practice_license', 'annual_practice_license'), ('premises_registration_license', 'premises_registration_license')], max_length=50),
        ),
    ]
