# Generated by Django 3.2.7 on 2022-03-06 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderlicense',
            name='customer_profile',
        ),
        migrations.AddField(
            model_name='riderlicense',
            name='name',
            field=models.CharField(choices=[('driving_license', 'driving_license'), ('id_front', 'id_front'), ('id_back', 'id_back')], default='id_front', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderlicense',
            name='rider_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_licenses', to='authentication.riderprofile'),
        ),
    ]
