# Generated by Django 3.2.7 on 2022-03-06 08:23

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20220306_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('rider_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_pic', to='authentication.riderprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
