# Generated by Django 3.2.7 on 2022-05-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_riderprofile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentriderlocation',
            name='rider_profile',
        ),
        migrations.AddField(
            model_name='currentriderlocation',
            name='rider',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='authentication.user'),
            preserve_default=False,
        ),
    ]
