# Generated by Django 3.2.7 on 2021-10-04 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0004_alter_medication_type'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payment_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='medication',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='medication.medication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('POD', 'Pay on delivery'), ('MPESA', 'MPESA'), ('VISA', 'Visa Card'), ('MASTERCARD', 'Master Card')], max_length=50),
        ),
    ]
