# Generated by Django 3.2.7 on 2021-10-26 15:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20211025_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
