# Generated by Django 3.2.7 on 2021-10-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_image_order_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('MPESA', 'MPESA'), ('CARD', 'Visa/Mastercard Card')], max_length=50),
        ),
    ]
