# Generated by Django 3.2.7 on 2021-11-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='charged_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_phone_no',
            field=models.CharField(default=4353435, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='event_id',
            field=models.CharField(default=323, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='status', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(max_length=30),
        ),
    ]
