# Generated by Django 3.2.7 on 2021-11-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20211122_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='event_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
