# Generated by Django 3.2.7 on 2022-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20211211_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='action_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='currentorderlocation',
            name='lat',
            field=models.DecimalField(decimal_places=40, max_digits=45),
        ),
        migrations.AlterField(
            model_name='currentorderlocation',
            name='long',
            field=models.DecimalField(decimal_places=40, max_digits=45),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=40, max_digits=45),
        ),
        migrations.AlterField(
            model_name='location',
            name='long',
            field=models.DecimalField(decimal_places=40, max_digits=45),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected')], default='Received', max_length=30),
        ),
    ]
