# Generated by Django 3.2.7 on 2022-02-01 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0018_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider_earning', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pharmacy_earning', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='riderearining',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'received'), ('accepted', 'accepted'), ('dispatched', 'dispatched'), ('delivered', 'delivered'), ('canceled', 'canceled'), ('rejected', 'rejected')], default='received', max_length=30),
        ),
        migrations.DeleteModel(
            name='PharmacyEarining',
        ),
        migrations.DeleteModel(
            name='RiderEarining',
        ),
        migrations.AddField(
            model_name='orderearning',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earning', to='order.order'),
        ),
        migrations.AddField(
            model_name='orderearning',
            name='pharmacist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_earnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderearning',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_earnings', to=settings.AUTH_USER_MODEL),
        ),
    ]
