# Generated by Django 3.2.7 on 2022-02-02 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0012_alter_pharmacystock_price'),
        ('order', '0019_auto_20220201_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderearning',
            name='pharmacist',
        ),
        migrations.AddField(
            model_name='orderearning',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_earnings', to='medication.pharmacy'),
        ),
    ]
