# Generated by Django 3.2.7 on 2022-03-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_riderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_rider_found',
            field=models.BooleanField(default=False),
        ),
    ]
