# Generated by Django 3.2.7 on 2022-04-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_order_is_rider_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderhistory',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
