# Generated by Django 3.2.7 on 2022-05-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_riderhistory_is_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderhistory',
            name='is_canceled',
        ),
        migrations.AlterField(
            model_name='riderhistory',
            name='is_accepted',
            field=models.BooleanField(null=True),
        ),
    ]
